import { OperatorStorage } from "@/services/operators-storage";
import { UserStorage } from "@/services/users-storage";
import { CourseClassStorage } from "@/services/course-classes-storage";
import { CourseClassFileStorage } from "@/services/course-class-files-storage";
import { CourseEnrollmentStorage } from "@/services/course-enrollments-storage";
import { CoursePaymentStorage } from "@/services/course-payments-storage";
import { ContactStorage } from "@/services/contacts-storage";
import { PasswordResetAttemptStorage } from "@/services/password-reset-attempts-storage";
import { RabbiBioStorage } from "@/services/rabbi-bio-storage";
import { CommunityUserStorage } from "@/services/community-users-storage";
import { ForumStorage } from "@/services/forums-storage";
import { CouponStorage } from "@/services/coupons-storage";
import { BookStorage } from "@/services/books-storage";
import { BookSaleStorage } from "@/services/book-sales-storage";
import { ChatStorage } from "@/services/chat-storage";
import { EmailTemplateStorage } from "@/services/email-templates-storage";
import { EmailGroupStorage } from "@/services/email-groups-storage";
import { EmailCampaignStorage } from "@/services/email-campaigns-storage";
import { EmailSpoolerStorage } from "@/services/email-spooler-storage";
import { CrmContactStorage } from "@/services/crm-contacts-storage";
import { CrmTagStorage } from "@/services/crm-tags-storage";
import { CrmCampaignStorage } from "@/services/crm-campaigns-storage";
import { CrmCampaignContactStorage } from "@/services/crm-campaign-contacts-storage";
import { processEmailSpooler } from "@/lib/email-spooler-cron";

export async function Boot() {
  await UserStorage.ensureIndexes();
  await CourseClassStorage.ensureIndexes();
  await CourseClassFileStorage.ensureIndexes();
  await CourseEnrollmentStorage.ensureIndexes();
  await CoursePaymentStorage.ensureIndexes();
  await ContactStorage.ensureIndexes();
  await PasswordResetAttemptStorage.ensureIndexes();
  await RabbiBioStorage.ensureIndexes();
  await CommunityUserStorage.ensureIndexes();
  await CouponStorage.ensureIndexes();
	await BookStorage.ensureIndexes();
	await BookSaleStorage.ensureIndexes();
	await ChatStorage.ensureIndexes();
  await EmailTemplateStorage.ensureIndexes();
  await EmailGroupStorage.ensureIndexes();
  await EmailCampaignStorage.ensureIndexes();
  await EmailSpoolerStorage.ensureIndexes();
  await CrmContactStorage.ensureIndexes();
  await CrmTagStorage.ensureIndexes();
  await CrmCampaignStorage.ensureIndexes();
  await CrmCampaignContactStorage.ensureIndexes();
  await ForumStorage.ensureSystemThreads();
  await OperatorStorage.ensureDefaultOperator();

  processEmailSpooler();
  setInterval(() => processEmailSpooler(), 60_000);
}
