import type { AdminKind, EntityConfig } from "@/app/admin/components/admin-collection-manager";

export const configs: Record<AdminKind, EntityConfig> = {
  "course-categories": {
    api: "/api/admin/course-categories",
    singular: "course category",
    plural: "course categories",
    fields: [
      { name: "name", label: "Name" },
      { name: "description", label: "Description", type: "textarea", span: "full" },
      { name: "enabled", label: "Enabled", type: "checkbox" },
    ],
    columns: [
      { label: "Category", value: (item) => String(item.name ?? "") },
      { label: "Slug", value: (item) => String(item.slug ?? "") },
      { label: "Enabled", value: (item) => (item.enabled ? "Yes" : "No") },
      { label: "Description", value: (item) => String(item.description ?? "") },
    ],
  },
  courses: {
    api: "/api/admin/courses",
    singular: "course",
    plural: "courses",
    fields: [
      { name: "title", label: "Title" },
      { name: "slug", label: "Slug" },
      { name: "category", label: "Category" },
      { name: "level", label: "Level", type: "select", options: ["Beginner", "Intermediate", "Advanced"] },
      { name: "price", label: "Price", type: "number" },
      { name: "communityPrice", label: "Community price", type: "number" },
      { name: "duration", label: "Duration" },
      { name: "startDate", label: "Start date" },
      { name: "endDate", label: "End date" },
      { name: "instructor", label: "Instructor" },
      { name: "status", label: "Status", type: "select", options: ["draft", "published", "archived"] },
      { name: "stripePaymentLink", label: "Stripe link" },
      { name: "summary", label: "Summary", type: "textarea", span: "full" },
      { name: "description", label: "Description", type: "textarea", span: "full" },
      { name: "includes", label: "Includes", type: "textarea-list", span: "full" },
      { name: "outcomes", label: "Outcomes", type: "textarea-list", span: "full" },
    ],
    columns: [
      { label: "Course", value: (item) => String(item.title ?? "") },
      { label: "Level", value: (item) => String(item.level ?? "") },
      { label: "Price", value: (item) => `$${Number(item.price ?? 0)}` },
      { label: "Status", value: (item) => String(item.status ?? "") },
      { label: "Start", value: (item) => String(item.startDate ?? "") },
    ],
  },
  papers: {
    api: "/api/admin/papers",
    singular: "paper",
    plural: "papers",
    fields: [
      { name: "title", label: "Title" },
      { name: "slug", label: "Slug" },
      { name: "category", label: "Category" },
      { name: "date", label: "Date" },
      { name: "author", label: "Author" },
      { name: "status", label: "Status", type: "select", options: ["draft", "published", "archived"] },
      { name: "visibility", label: "Visibility", type: "select", options: ["public", "community", "private"] },
      { name: "summary", label: "Summary", type: "textarea", span: "full" },
      { name: "content", label: "Content", type: "textarea", span: "full" },
    ],
    columns: [
      { label: "Paper", value: (item) => String(item.title ?? "") },
      { label: "Category", value: (item) => String(item.category ?? "") },
      { label: "Visibility", value: (item) => String(item.visibility ?? "") },
      { label: "Status", value: (item) => String(item.status ?? "") },
      { label: "Date", value: (item) => String(item.date ?? "") },
    ],
  },
  forums: {
    api: "/api/admin/forums",
    singular: "thread",
    plural: "threads",
    fields: [
      { name: "title", label: "Title" },
      { name: "slug", label: "Slug" },
      { name: "area", label: "Area" },
      { name: "courseSlug", label: "Course slug" },
      { name: "status", label: "Status", type: "select", options: ["open", "closed", "hidden"] },
      { name: "featured", label: "Featured", type: "checkbox" },
      { name: "repliesCount", label: "Replies", type: "number" },
      { name: "unreadCount", label: "Unread", type: "number" },
      { name: "lastActivityAt", label: "Last activity" },
    ],
    columns: [
      { label: "Thread", value: (item) => String(item.title ?? "") },
      { label: "Area", value: (item) => String(item.area ?? "") },
      { label: "Replies", value: (item) => String(item.repliesCount ?? 0) },
      { label: "Status", value: (item) => String(item.status ?? "") },
      { label: "Featured", value: (item) => (item.featured ? "Yes" : "No") },
    ],
  },
  instructors: {
    api: "/api/admin/instructors",
    singular: "instructor",
    plural: "instructors",
    fields: [
      { name: "firstName", label: "First name" },
      { name: "lastName", label: "Last name" },
      { name: "displayName", label: "Display name" },
      { name: "email", label: "Email" },
      { name: "photoUrl", label: "Photo URL" },
      { name: "enabled", label: "Enabled", type: "checkbox" },
      { name: "bio", label: "Bio", type: "textarea", span: "full" },
    ],
    columns: [
      { label: "Instructor", value: (item) => String(item.displayName ?? "") },
      { label: "Email", value: (item) => String(item.email ?? "") },
      { label: "Slug", value: (item) => String(item.slug ?? "") },
      { label: "Enabled", value: (item) => (item.enabled ? "Yes" : "No") },
    ],
  },
  users: {
    api: "/api/admin/users",
    singular: "user",
    plural: "users",
    noCreate: true,
    fields: [
      { name: "firstName", label: "First name" },
      { name: "lastName", label: "Last name" },
      { name: "email", label: "Email" },
      { name: "country", label: "Country" },
      { name: "state", label: "State" },
      { name: "city", label: "City" },
      { name: "role", label: "Role" },
      { name: "status", label: "Status", type: "select", options: ["active", "disabled", "pending"] },
      { name: "communityStatus", label: "Community", type: "select", options: ["none", "active", "cancelled", "manual"] },
    ],
    columns: [
      { label: "User", value: (item) => `${String(item.firstName ?? "")} ${String(item.lastName ?? "")}`.trim() },
      { label: "Email", value: (item) => String(item.email ?? "") },
      { label: "Location", value: (item) => [item.city, item.state, item.country].filter(Boolean).join(", ") },
      { label: "Role", value: (item) => String(item.role ?? "") },
      { label: "Status", value: (item) => String(item.status ?? "") },
      { label: "Community", value: (item) => String(item.communityStatus ?? "") },
    ],
  },
  coupons: {
    api: "/api/admin/coupons",
    singular: "coupon",
    plural: "coupons",
    fields: [
      { name: "code", label: "Code" },
      { name: "percentOff", label: "Percent off", type: "number" },
      { name: "scope", label: "Scope", type: "select", options: ["all", "course", "community"] },
      { name: "courseUuid", label: "Course UUID" },
      { name: "active", label: "Active", type: "checkbox" },
      { name: "expiresAt", label: "Expires at" },
      { name: "usageLimit", label: "Usage limit", type: "number" },
      { name: "usageCount", label: "Usage count", type: "number" },
    ],
    columns: [
      { label: "Code", value: (item) => String(item.code ?? "") },
      { label: "Percent", value: (item) => `${Number(item.percentOff ?? 0)}%` },
      { label: "Scope", value: (item) => String(item.scope ?? "") },
      { label: "Active", value: (item) => (item.active ? "Yes" : "No") },
      { label: "Usage", value: (item) => `${item.usageCount ?? 0}/${item.usageLimit ?? 0}` },
    ],
  },
};
